# Generated by Django 3.2.19 on 2025-12-14 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('disciplina', models.CharField(max_length=100)),
                ('enunciado', models.TextField()),
                ('resposta', models.CharField(max_length=10)),
                ('texto_01', models.TextField(blank=True, null=True)),
                ('texto_02', models.TextField(blank=True, null=True)),
                ('texto_04', models.TextField(blank=True, null=True)),
                ('texto_08', models.TextField(blank=True, null=True)),
                ('texto_16', models.TextField(blank=True, null=True)),
                ('texto_32', models.TextField(blank=True, null=True)),
                ('texto_64', models.TextField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='questoes/')),
                ('prova', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questoes.prova')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='TextoApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='textos_apoio_img/')),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('fonte', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tentativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_questoes', models.IntegerField()),
                ('pontuacao', models.FloatField(default=0.0)),
                ('total', models.IntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questoes.prova')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespostaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_marcada', models.TextField()),
                ('acertou_totalmente', models.BooleanField(default=False)),
                ('pontos_obtidos', models.FloatField(default=0.0)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questoes.questao')),
                ('tentativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questoes.tentativa')),
            ],
        ),
    ]
