# Generated by Django 3.2.19 on 2025-11-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(db_index=True)),
                ('enunciado', models.TextField()),
                ('alternativa_01', models.TextField(blank=True, null=True)),
                ('alternativa_02', models.TextField(blank=True, null=True)),
                ('alternativa_04', models.TextField(blank=True, null=True)),
                ('alternativa_08', models.TextField(blank=True, null=True)),
                ('alternativa_16', models.TextField(blank=True, null=True)),
                ('alternativa_32', models.TextField(blank=True, null=True)),
                ('alternativa_64', models.TextField(blank=True, null=True)),
                ('resposta', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tentativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('qtd_questoes', models.PositiveIntegerField()),
                ('pontuacao', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
