# Generated by Django 3.2.19 on 2025-11-25 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentativa',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tentativas', to='auth.user'),
            preserve_default=False,
        ),
    ]
