const dados = [{
    "UFSC": {
        "FLORIANÓPOLIS": [
            { curso: "ADMINISTRAÇÃO", turno: "MATUTINO", notaCorte: 49.96, vagas: 35.0 },
            { curso: "ADMINISTRAÇÃO", turno: "NOTURNO", notaCorte: 49.15, vagas: 35.0 },
            { curso: "AGRONOMIA", turno: "INTEGRAL", notaCorte: 24.32, vagas: 38.0 },
            { curso: "ANIMAÇÃO", turno: "INTEGRAL", notaCorte: 63.77, vagas: 14.0 },
            { curso: "ANTROPOLOGIA", turno: "VESPERTINO", notaCorte: 32.6, vagas: 9.0 },
            { curso: "ARQUITETURA E URBANISMO", turno: "INTEGRAL", notaCorte: 66.9, vagas: 28.0 },
            { curso: "ARTES CÊNICAS", turno: "NOTURNO", notaCorte: 53.57, vagas: 10.0 },
            { curso: "BIBLIOTECONOMIA", turno: "NOTURNO", notaCorte: 25.3, vagas: 21.0 },
            { curso: "CIÊNCIA DA INFORMAÇÃO", turno: "INTEGRAL", notaCorte: 53.95, vagas: 14.0 },
            { curso: "CIÊNCIA E TEC. DE ALIMENTOS", turno: "INT", notaCorte: 27.51, vagas: 24.0 },
            { curso: "CIÊNCIAS BIOLÓGICAS", turno: "INTEGRAL", notaCorte: 63.24, vagas: 28.0 },
            { curso: "CIÊNCIAS BIOLÓGICAS", turno: "NOTURNO", notaCorte: 29.34, vagas: 28.0 },
            { curso: "CIÊNCIAS CONTÁBEIS", turno: "MATUTINO", notaCorte: 30.05, vagas: 31.0 },
            { curso: "CIÊNCIAS CONTÁBEIS", turno: "NOTURNO", notaCorte: 35.7, vagas: 31.0 },
            { curso: "CIÊNCIAS DA COMPUTAÇÃO", turno: "INTEGRAL", notaCorte: 67.51, vagas: 35.0 },
            { curso: "CIÊNCIAS ECONÔMICAS", turno: "MATUTINO", notaCorte: 50.35, vagas: 31.0 },
            { curso: "CIÊNCIAS ECONÔMICAS", turno: "NOTURNO", notaCorte: 40.65, vagas: 31.0 },
            { curso: "CIÊNCIAS SOCIAIS", turno: "MATUTINO", notaCorte: 43.21, vagas: 15.0 },
            { curso: "CIÊNCIAS SOCIAIS", turno: "NOTURNO", notaCorte: 31.43, vagas: 17.0 },
            { curso: "CINEMA", turno: "INTEGRAL", notaCorte: 66.3, vagas: 10.0 },
            { curso: "DESIGN", turno: "INTEGRAL", notaCorte: 65.35, vagas: 14.0 },
            { curso: "DESIGN DE PRODUTO", turno: "INTEGRAL", notaCorte: 52.18, vagas: 14.0 },
            { curso: "DIREITO", turno: "MATUTINO", notaCorte: 72.47, vagas: 31.0 },
            { curso: "DIREITO", turno: "NOTURNO", notaCorte: 69.89, vagas: 31.0 },
            { curso: "EDUCAÇÃO FÍSICA", turno: "VESPERTINO", notaCorte: 45.08, vagas: 21.0 },
            { curso: "ENFERMAGEM", turno: "INTEGRAL", notaCorte: 52.02, vagas: 26.0 },
            { curso: "ENG. DE AQUICULTURA", turno: "INTEGRAL", notaCorte: 28.44, vagas: 28.0 },
            { curso: "ENG. DE CONTROLE E AUTOMAÇÃO", turno: "INT", notaCorte: 59.66, vagas: 25.0 },
            { curso: "ENGENHARIA CIVIL", turno: "INTEGRAL", notaCorte: 52.93, vagas: 38.0 },
            { curso: "ENGENHARIA DE ALIMENTOS", turno: "INTEGRAL", notaCorte: 33.36, vagas: 17.0 },
            { curso: "ENGENHARIA DE MATERIAIS", turno: "INTEGRAL", notaCorte: 43.78, vagas: 24.0 },
            { curso: "ENGENHARIA DE PRODUÇÃO", turno: "INTEGRAL", notaCorte: 53.11, vagas: 42.0 },
            { curso: "ENGENHARIA ELETRÔNICA", turno: "INTEGRAL", notaCorte: 49.36, vagas: 21.0 },
            { curso: "ENGENHARIA MECÂNICA", turno: "INTEGRAL", notaCorte: 66.43, vagas: 38.0 },
            { curso: "ENGENHARIA QUÍMICA", turno: "INTEGRAL", notaCorte: 62.62, vagas: 17.0 },
            { curso: "ENG. SANITÁRIA E AMBIENTAL", turno: "INT", notaCorte: 30.07, vagas: 31.0 },
            { curso: "FARMÁCIA", turno: "INTEGRAL", notaCorte: 58.65, vagas: 45.0 },
            { curso: "FILOSOFIA", turno: "NOTURNO", notaCorte: 31.92, vagas: 13.0 },
            { curso: "FILOSOFIA", turno: "VESPERTINO", notaCorte: 34.58, vagas: 13.0 },
            { curso: "FÍSICA", turno: "INTEGRAL", notaCorte: 33.48, vagas: 19.0 },
            { curso: "FÍSICA", turno: "NOTURNO", notaCorte: 32.4, vagas: 26.0 },
            { curso: "FONOAUDIOLOGIA", turno: "INTEGRAL", notaCorte: 53.42, vagas: 14.0 },
            { curso: "GEOGRAFIA", turno: "MATUTINO", notaCorte: 28.28, vagas: 14.0 },
            { curso: "GEOGRAFIA", turno: "NOTURNO", notaCorte: 26.98, vagas: 14.0 },
            { curso: "GEOLOGIA", turno: "INTEGRAL", notaCorte: 36.75, vagas: 10.0 },
            { curso: "HISTÓRIA", turno: "MATUTINO", notaCorte: 57.74, vagas: 16.0 },
            { curso: "HISTÓRIA", turno: "NOTURNO", notaCorte: 49.83, vagas: 16.0 },
            { curso: "JORNALISMO", turno: "INTEGRAL", notaCorte: 63.21, vagas: 21.0 },
            { curso: "LETRAS ALEMÃO", turno: "VESPERTINO", notaCorte: 34.66, vagas: 14.0 },
            { curso: "LETRAS", turno: "MATUTINO", notaCorte: 27.73, vagas: 14.0 },
            { curso: "LETRAS", turno: "MATUTINO", notaCorte: 32.5, vagas: 14.0 },
            { curso: "LETRAS", turno: "VESPERTINO", notaCorte: 54.05, vagas: 14.0 },
            { curso: "LETRAS", turno: "MATUTINO", notaCorte: 39.74, vagas: 14.0 },
            { curso: "LETRAS", turno: "INTEGRAL", notaCorte: 39.1, vagas: 28.0 },
            { curso: "LETRAS", turno: "NOTURNO", notaCorte: 38.48, vagas: 14.0 },
            { curso: "MATEMÁTICA", turno: "INTEGRAL", notaCorte: 36.8, vagas: 14.0 },
            { curso: "MATEMÁTICA", turno: "MATUTINO", notaCorte: 24.28, vagas: 38.0 },
            { curso: "MEDICINA", turno: "INTEGRAL", notaCorte: 86.21, vagas: 35.0 },
            { curso: "METEOROLOGIA", turno: "INTEGRAL", notaCorte: 38.28, vagas: 10.0 },
            { curso: "MUSEOLOGIA", turno: "INTEGRAL", notaCorte: 35.9, vagas: 10.0 },
            { curso: "NUTRIÇÃO", turno: "INTEGRAL", notaCorte: 62.31, vagas: 16.0 },
            { curso: "OCEANOGRAFIA", turno: "INTEGRAL", notaCorte: 46.11, vagas: 10.0 },
            { curso: "ODONTOLOGIA", turno: "INTEGRAL", notaCorte: 59.44, vagas: 35.0 },
            { curso: "PEDAGOGIA", turno: "VESPERTINO", notaCorte: 28.75, vagas: 35.0 },
            { curso: "QUÍMICA", turno: "INTEGRAL", notaCorte: 29.39, vagas: 28.0 },
            { curso: "QUÍMICA", turno: "INTEGRAL", notaCorte: 31.8, vagas: 14.0 },
            { curso: "QUÍMICA TECNOLÓGICA", turno: "INTEGRAL", notaCorte: 31.79, vagas: 14.0 },
            { curso: "RELAÇÕES INTERNACIONAIS", turno: "VESP", notaCorte: 68.08, vagas: 28.0 },
            { curso: "SECRETARIADO EXECUTIVO", turno: "NOTURNO", notaCorte: 29.77, vagas: 14.0 },
            { curso: "SERVIÇO SOCIAL", turno: "NOTURNO", notaCorte: 16.15, vagas: 31.0 },
            { curso: "SISTEMAS DE INFORMAÇÃO", turno: "NOTURNO", notaCorte: 62.54, vagas: 35.0 },
            { curso: "ZOOTECNIA", turno: "INTEGRAL", notaCorte: 27.34, vagas: 24.0 },
        ],
        "CURITIBANOS": [
            { curso: "AGRONOMIA", turno: "INTEGRAL", notaCorte: 20.85, vagas: 35.0 },
            { curso: "ENGENHARIA FLORESTAL", turno: "INTEGRAL", notaCorte: 27.5, vagas: 21.0 },
            { curso: "MEDICINA VETERINÁRIA", turno: "INTEGRAL", notaCorte: 48.42, vagas: 28.0 },
        ],
        "JOINVILLE": [
            { curso: "CIÊNCIA E TECNOLOGIA", turno: "INTEGRAL", notaCorte: 43.34, vagas: 21.0 },
            { curso: "ENG. CIVIL DE INFRAESTRUTURA", turno: "INT", notaCorte: 39.27, vagas: 17.0 },
            { curso: "ENG. DE TRANSP. E LOG.", turno: "INTEGRAL", notaCorte: 26.87, vagas: 17.0 },
            { curso: "ENGENHARIA AEROESPACIAL", turno: "INTEGRAL", notaCorte: 71.15, vagas: 17.0 },
            { curso: "ENGENHARIA AUTOMOTIVA", turno: "INTEGRAL", notaCorte: 53.15, vagas: 17.0 },
            { curso: "ENGENHARIA MECATRÔNICA", turno: "INTEGRAL", notaCorte: 63.59, vagas: 17.0 },
            { curso: "ENGENHARIA NAVAL", turno: "INTEGRAL", notaCorte: 42.33, vagas: 17.0 },
            { curso: "ENG. FERROV. E METROVIÁRIA", turno: "INT", notaCorte: 39.56, vagas: 14.0 },
        ],
        "ARARANGUÁ": [
            { curso: "ENG. DE COMPUTAÇÃO", turno: "INTEGRAL", notaCorte: 56.14, vagas: 21.0 },
            { curso: "ENGENHARIA DE ENERGIA", turno: "INTEGRAL", notaCorte: 26.39, vagas: 21.0 },
            { curso: "FISIOTERAPIA", turno: "INTEGRAL", notaCorte: 46.18, vagas: 21.0 },
            { curso: "MEDICINA", turno: "INTEGRAL", notaCorte: 83.5, vagas: 21.0 },
            { curso: "TEC. DA INFO. E COMUNICAÇÃO", turno: "NOT", notaCorte: 51.02, vagas: 21.0 },
        ],
        "BLUMENAU": [
            { curso: "ENG. DE CONTROLE E AUTOMAÇÃO", turno: "INT", notaCorte: 31.17, vagas: 35.0 },
            { curso: "ENGENHARIA DE MATERIAIS", turno: "INTEGRAL", notaCorte: 23.62, vagas: 35.0 },
            { curso: "ENGENHARIA TÊXTIL", turno: "MATUTINO", notaCorte: 32.45, vagas: 35.0 },
            { curso: "MATEMÁTICA", turno: "MATUTINO", notaCorte: 38.92, vagas: 17.0 },
            { curso: "MATEMÁTICA", turno: "NOTURNO", notaCorte: 38.52, vagas: 17.0 },
            { curso: "QUÍMICA", turno: "INTEGRAL", notaCorte: 32.92, vagas: 17.0 },
            { curso: "QUÍMICA", turno: "NOTURNO", notaCorte: 39.59, vagas: 17.0 },
            ],
        }
    },
    {   
    "IFC": {
        "ARAQUARI": [
            { curso: "AGRONOMIA", turno: "INTEGRAL", notaCorte: 26.14, vagas: 10.0 },
            { curso: "CIÊNCIAS AGRÍCOLAS", turno: "NOTURNO", notaCorte: 29.63, vagas: 10.0 },
            { curso: "MEDICINA VETERINÁRIA", turno: "INTEGRAL", notaCorte: 51.5, vagas: 10.0 },
            { curso: "QUÍMICA", turno: "NOTURNO", notaCorte: 27.46, vagas: 10.0 },
            { curso: "REDES DE COMPUTADORES", turno: "NOTURNO", notaCorte: 25.21, vagas: 10.0 },
            { curso: "SISTEMAS DE INFORMAÇÃO", turno: "MATUTINO", notaCorte: 30.07, vagas: 10.0 },
        ],
        "CAMBORIÚ": [
            { curso: "AGRONOMIA", turno: "INTEGRAL", notaCorte: 29.55, vagas: 10.0 },
            { curso: "MATEMÁTICA", turno: "NOTURNO", notaCorte: 33.27, vagas: 10.0 },
            { curso: "NEGÓCIOS IMOBILIÁRIOS", turno: "NOTURNO", notaCorte: 29.53, vagas: 10.0 },
            { curso: "PEDAGOGIA", turno: "NOTURNO", notaCorte: 2.0, vagas: 10.0 },
            { curso: "SISTEMAS DE INFORMAÇÃO", turno: "MATUTINO", notaCorte: 29.64, vagas: 10.0 },
            { curso: "SISTEMAS PARA INTERNET", turno: "EAD", notaCorte: 28.52, vagas: 10.0 },
        ],
        "CONCÓRDIA": [
            { curso: "AGRONOMIA", turno: "INTEGRAL", notaCorte: 25.05, vagas: 10.0 },
            { curso: "ENGENHARIA DE ALIMENTOS", turno: "INTEGRAL", notaCorte: 20.66, vagas: 10.0 },
            { curso: "MATEMÁTICA", turno: "NOTURNO", notaCorte: 36.93, vagas: 10.0 },
            { curso: "MEDICINA VETERINÁRIA", turno: "INTEGRAL", notaCorte: 45.56, vagas: 10.0 },
        ],
        "SANTA ROSA DO SUL": [
            { curso: "AGRONOMIA", turno: "INTEGRAL", notaCorte: 18.47, vagas: 20.0 },
            { curso: "ZOOTECNIA", turno: "INTEGRAL", notaCorte: 28.68, vagas: 10.0 },
        ],
        "RIO DO SUL": [
            { curso: "AGRONOMIA", turno: "INTEGRAL", notaCorte: 21.78, vagas: 20.0 },
            { curso: "CIÊNCIA DA COMPUTAÇÃO", turno: "INTEGRAL", notaCorte: 34.39, vagas: 10.0 },
            { curso: "ENGENHARIA MECATRÔNICA", turno: "INTEGRAL", notaCorte: 28.88, vagas: 10.0 },
            { curso: "FÍSICA", turno: "NOTURNO", notaCorte: 38.81, vagas: 9.0 },
            { curso: "MATEMÁTICA", turno: "NOTURNO", notaCorte: 30.43, vagas: 10.0 },
            { curso: "PEDAGOGIA", turno: "NOTURNO", notaCorte: 25.95, vagas: 10.0 },
        ],
        "VIDEIRA": [
            { curso: "AGRONOMIA", turno: "MATUTINO", notaCorte: 32.95, vagas: 10.0 },
            { curso: "CIÊNCIA DA COMPUTAÇÃO", turno: "INTEGRAL", notaCorte: 27.12, vagas: 10.0 },
            { curso: "ENGENHARIA ELÉTRICA", turno: "NOTURNO", notaCorte: 19.51, vagas: 10.0 },
            { curso: "PEDAGOGIA", turno: "NOTURNO", notaCorte: 27.8, vagas: 10.0 },
        ],
        "FRAIBURGO": [
            { curso: "ANÁLISE E DESENVOLVIMENTO DE SISTEMAS", turno: "NOTURNO", notaCorte: 37.95, vagas: 10.0 },
        ],
        "BLUMENAU": [
            { curso: "CIÊNCIA DA COMPUTAÇÃO", turno: "INTEGRAL", notaCorte: 26.55, vagas: 10.0 },
            { curso: "ENGENHARIA ELÉTRICA", turno: "NOTURNO", notaCorte: 27.3, vagas: 10.0 },
            { curso: "PEDAGOGIA", turno: "NOTURNO", notaCorte: 29.42, vagas: 10.0 },
        ],
        "IBIRAMA": [
            { curso: "DESIGN DE MODA", turno: "NOTURNO", notaCorte: 31.94, vagas: 7.0 },
        ],
        "SÃO BENTO DO SUL": [
            { curso: "ENGENHARIA DE COMPUTAÇÃO", turno: "INTEGRAL", notaCorte: 31.68, vagas: 10.0 },
            { curso: "ENGENHARIA DE CONTROLE E AUTOMAÇÃO", turno: "INTEGRAL", notaCorte: 37.08, vagas: 10.0 },
        ],
        "LUZERNA": [
            { curso: "ENGENHARIA DE CONTROLE E AUTOMAÇÃO", turno: "INTEGRAL", notaCorte: 28.84, vagas: 10.0 },
            { curso: "ENGENHARIA MECÂNICA", turno: "INTEGRAL", notaCorte: 38.79, vagas: 10.0 },
        ],
        "SÃO FRANCISCO DO SUL": [
            { curso: "ENGENHARIA ELÉTRICA", turno: "NOTURNO", notaCorte: 29.93, vagas: 10.0 },
            { curso: "LOGÍSTICA", turno: "NOTURNO", notaCorte: 32.63, vagas: 10.0 },
        ],
        "SOMBRIO": [
            { curso: "GESTÃO DE TURISMO", turno: "NOTURNO", notaCorte: 34.23, vagas: 10.0 },
            { curso: "REDES DE COMPUTADORES", turno: "NOTURNO", notaCorte: 26.8, vagas: 10.0 },
        ],
        "BRUSQUE": [
            { curso: "QUÍMICA", turno: "NOTURNO", notaCorte: 22.18, vagas: 10.0 },
            { curso: "REDES DE COMPUTADORES", turno: "NOTURNO", notaCorte: 29.8, vagas: 10.0 },
            ],
        }
    },
    {
    "IFSC": {
        "CANOINHAS": [
            { curso: "AGRONOMIA", turno: "INTEGRAL", notaCorte: 20.07, vagas: 10.0 },
            { curso: "ALIMENTOS", turno: "NOTURNO", notaCorte: 32.79, vagas: 10.0 },
            { curso: "ANÁLISE E DESENVOLVIMENTO DE SIST", turno: "NOTURNO", notaCorte: 28.75, vagas: 10.0 },
        ],
        "SÃO MIGUEL DO OESTE": [
            { curso: "AGRONOMIA", turno: "MATUTINO", notaCorte: 25.85, vagas: 10.0 },
            { curso: "ALIMENTOS", turno: "NOTURNO", notaCorte: 33.93, vagas: 10.0 },
            { curso: "PROCESSOS GERENCIAS", turno: "NOTURNO", notaCorte: 24.57, vagas: 10.0 },
        ],
        "TUBARÃO": [
            { curso: "ANÁLISE E DESENVOLV DE SIST", turno: "NOT.", notaCorte: 44.59, vagas: 10.0 },
            { curso: "PROCESSOS GERENCIAS", turno: "NOTURNO", notaCorte: 39.04, vagas: 10.0 },
            { curso: "SISTEMAS EMBARCADOS", turno: "VESPERTINO", notaCorte: 38.35, vagas: 10.0 },
        ],
        "GASPAR": [
            { curso: "ANÁLISE E DESENVOLVIMENTO DE SIST", turno: "NOTURNO", notaCorte: 43.74, vagas: 10.0 },
            { curso: "DESIGN DE MODA", turno: "NOTURNO", notaCorte: 27.52, vagas: 10.0 },
            { curso: "PROCESSOS GERENCIAS", turno: "NOTURNO", notaCorte: 29.12, vagas: 10.0 },
        ],
        "SÃO JOSÉ": [
            { curso: "ANÁLISE E DESENVOLVIMENTO DE SIST", turno: "NOTURNO", notaCorte: 56.29, vagas: 10.0 },
            { curso: "ENG DE TELECOMUNICAÇÕES", turno: "INTEGRAL", notaCorte: 38.32, vagas: 10.0 },
        ],
        "LAGES": [
            { curso: "CIÊNCIA DA COMPUTAÇÃO", turno: "MATUTINO", notaCorte: 51.44, vagas: 10.0 },
            { curso: "ENGENHARIA MECÂNICA", turno: "MATUTINO", notaCorte: 27.73, vagas: 10.0 },
            { curso: "ENGENHARIA QUÍMICA", turno: "MATUTINO", notaCorte: 28.68, vagas: 7.0 },
            { curso: "GESTÃO DO AGRONEGÓCIO", turno: "NOTURNO", notaCorte: 28.48, vagas: 10.0 },
        ],
        "FLORIANÓPOLIS": [
            { curso: "DESIGN", turno: "INTEGRAL", notaCorte: 45.7, vagas: 7.0 },
            { curso: "ELETRÔNICA INDUSTRIAL", turno: "NOTURNO", notaCorte: 35.63, vagas: 10.0 },
            { curso: "ENGENHARIA CIVIL", turno: "INTEGRAL", notaCorte: 47.13, vagas: 10.0 },
            { curso: "ENGENHARIA ELÉTRICA", turno: "INTEGRAL", notaCorte: 24.62, vagas: 10.0 },
            { curso: "ENGENHARIA ELETRÔNICA", turno: "INTEGRAL", notaCorte: 31.26, vagas: 10.0 },
            { curso: "ENGENHARIA MECATRÔNICA", turno: "INTEGRAL", notaCorte: 47.16, vagas: 10.0 },
            { curso: "GASTRONOMIA", turno: "MATUTINO", notaCorte: 52.8, vagas: 10.0 },
            { curso: "GESTÃO DA TECNOLOGIA DA INFO", turno: "NOT", notaCorte: 53.18, vagas: 7.0 },
            { curso: "GESTÃO DO TURISMO", turno: "NOTURNO", notaCorte: 27.08, vagas: 10.0 },
            { curso: "HOTELARIA", turno: "MATUTINO", notaCorte: 25.98, vagas: 10.0 },
            { curso: "RADIOLOGIA", turno: "INTEGRAL", notaCorte: 30.34, vagas: 10.0 },
            { curso: "SISTEMAS DE ENERGIA", turno: "NOTURNO", notaCorte: 34.28, vagas: 10.0 },
        ],
        "ARARANGUÁ": [
            { curso: "DESIGN DE MODA", turno: "NOTURNO", notaCorte: 36.78, vagas: 10.0 },
            { curso: "LICENCIATURA EM FÍSICA", turno: "NOTURNO", notaCorte: 31.29, vagas: 10.0 },
        ],
        "JARAGUÁ DO SUL": [
            { curso: "DESIGN DE MODA", turno: "NOTURNO", notaCorte: 32.98, vagas: 10.0 },
            { curso: "ENGENHARIA ELÉTRICA", turno: "MATUTINO", notaCorte: 29.24, vagas: 10.0 },
            { curso: "ENGENHARIA MECÂNICA", turno: "VESPERTINO", notaCorte: 24.86, vagas: 10.0 },
            { curso: "LICENCIATURA EM FÍSICA", turno: "38.22", notaCorte: 10.0, vagas: 10.0 },
        ],
        "JOINVILLE": [
            { curso: "ENFERMAGEM", turno: "MAT", notaCorte: 45.75, vagas: 6.0 },
            { curso: "ENGENHARIA ELÉTRICA", turno: "NOTURNO", notaCorte: 48.05, vagas: 10.0 },
            { curso: "GESTÃO HOSPITALAR", turno: "VESP e NOT", notaCorte: 19.02, vagas: 10.0 },
        ],
        "CHAPECÓ": [
            { curso: "ENG DE CONTROLE E AUTOM", turno: "MAT e VESP", notaCorte: 33.48, vagas: 10.0 },
        ],
        "CRICIÚMA": [
            { curso: "ENGENHARIA CIVIL", turno: "INTEGRAL", notaCorte: 27.78, vagas: 10.0 },
            { curso: "ENGENHARIA MECATRÔNICA", turno: "INTEGRAL", notaCorte: 30.06, vagas: 10.0 },
            { curso: "LICENCIATURA EM QUÍMICA", turno: "39.86", notaCorte: 10.0, vagas: 10.0 },
        ],
        "SÃO CARLOS": [
            { curso: "ENGENHARIA CIVIL", turno: "INTEGRAL", notaCorte: 30.12, vagas: 10.0 },
        ],
        "URUPEMA": [
            { curso: "ENGENHARIA DE ALIMENTOS", turno: "MATUTINO", notaCorte: 36.04, vagas: 5.0 },
            { curso: "VITICULTURA E ENOLOGIA", turno: "VESP", notaCorte: 32.76, vagas: 6.0 },
        ],
        "CAÇADOR": [
            { curso: "ENGENHARIA DE PRODUÇÃO", turno: "NOTURNO", notaCorte: 22.68, vagas: 10.0 },
            { curso: "SISTEMAS DE INFORMAÇÃO", turno: "NOTURNO", notaCorte: 20.15, vagas: 10.0 },
        ],
        "ITAJAÍ": [
            { curso: "ENGENHARIA ELÉTRICA", turno: "VESPERTINO", notaCorte: 28.77, vagas: 10.0 },
        ],
        "XANXERÊ": [
            { curso: "ENGENHARIA MECÂNICA", turno: "NOTURNO", notaCorte: 31.05, vagas: 10.0 },
        ],
        "GAROPABA": [
            { curso: "GESTÃO AMBIENTAL", turno: "MATUTINO", notaCorte: 17.17, vagas: 10.0 },
            { curso: "SISTEMAS PARA INTERNET", turno: "NOTURNO", notaCorte: 23.19, vagas: 10.0 },
        ],
        "POLOS EAD": [
            { curso: "LICENCIATURA EM MATEMÁTICA", turno: "21.97", notaCorte: 120.0, vagas: 10.0 },
        ],
        "PALHOÇA": [
            { curso: "PRODUÇÃO MULTIMÍDIA", turno: "NOTURNO", notaCorte: 38.2, vagas: 10.0 },
            ],
        },
    }
];  
