# Generated by Django 3.2.19 on 2025-12-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(choices=[('UFSC', 'UFSC'), ('IFC', 'IFC'), ('IFSC', 'IFSC')], max_length=10)),
                ('cidade', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=100)),
                ('turno', models.CharField(max_length=50)),
                ('nota_corte', models.FloatField()),
                ('vagas', models.FloatField()),
            ],
            options={
                'ordering': ['instituicao', 'cidade', 'curso'],
            },
        ),
    ]
